library(dplyr)
library(multinma)
library(openxlsx)
library(ggraph)
library(tidyr)
devtools::load_all()

net <- readRDS("Data/network.RDs")

FE_Llogis <- fit_model(net, "fixed", llhood = "Loglogistic")
saveRDS(FE_Llogis, "Data/Models/FE_Llogis.RDs")
gc()
RE_Llogis <- fit_model(net, "random", llhood = "Loglogistic")
saveRDS(RE_Llogis, "Data/Models/RE_Llogis.RDs")
gc()
FE_Lnorm <- fit_model(net, "fixed", llhood = "Lognormal")
saveRDS(FE_Lnorm, "Data/Models/FE_Lnorm.RDs")
gc()
RE_Lnorm <- fit_model(net, "random", llhood = "Lognormal")
saveRDS(RE_Lnorm, "Data/Models/RE_Lnorm.RDs")
gc()
FE_Weib <- fit_model(net, "fixed", llhood = "weibull")
saveRDS(FE_Weib, "Data/Models/FE_Weib.RDs")
gc()
RE_Weib <- fit_model(net, "random", llhood = "weibull")
saveRDS(RE_Weib, "Data/Models/RE_Weib.RDs")