name: Build Thesis
on: [push]
jobs: 
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git Repo
        uses: actions/checkout@v2
      - name: Compile TeX
        run: python build.py
      - uses: actions/upload-artifact@v2
        with:
          name: main.pdf
          path: Thesis/main.pdf
